### ISSUE TITLE
Get enzyme to work with karma test runner

### ISSUE THREAD

**Issue by jasonlally** [DataSF/open-data-explorer#127]
I'm getting a series of errors when attempting to run a simple test using enzyme

Here's an example:
```
ERROR in ./~/htmlparser2/~/entities/maps/decode.json
Module parse failed: /Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/htmlparser2/node_modules/entities/maps/decode.json Unexpected token (1:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:4)
    at Parser.pp$4.raise (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/jasonlallymoci/Documents/workspace/open-data-explorer/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
 @ ./~/htmlparser2/~/entities/lib/decode_codepoint.js 1:16-46
```

Based on this issue here: https://github.com/davezuko/react-redux-starter-kit/issues/328 I've tried everything mentioned here and still can't get it working.

Once working, enzyme will allow us to write simpler tests of React components

As a side note, I'm coming up a huge learning curve on getting karma + webpack + react to play nicely. 

Code is currently on the branch '[feature/coverage](https://github.com/datasf/open-data-explorer/tree/feature/coverage)'

Here are the relevant files:

- [karma.conf.js](https://github.com/DataSF/open-data-explorer/blob/feature/coverage/karma.conf.js)
- [webpack/config.test.js](https://github.com/DataSF/open-data-explorer/blob/feature/coverage/webpack/config.test.js)
- [tests.webpack.js](https://github.com/DataSF/open-data-explorer/blob/feature/coverage/tests.webpack.js)

**Comment by jasonlally** [comment]
Addressed by #130
